name: Markdown CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: [self-hosted, linux, x64, csa-lab4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Run markdownlint
        env:
          npm_config_cache: ${{ runner.temp }}/npm-cache
        run: npx --yes markdownlint-cli@0.48.0 "**/*.md" --config .markdownlint.yaml --ignore "TASK/**"
